apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m0s # Reconcile every 5 minutes
  chart:
    spec:
      chart: grafana
      version: 6.56.0
      sourceRef:
        kind: HelmRepository
        name: grafana-repo
        namespace: flux-system
  values:
    adminUser: admin
    adminPassword: admin123 # Change to a secure password