apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "51.0.2"  # Check latest version at https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    grafana:
      adminPassword: "admin123"  # Change password
      service:
        type: NodePort # Change to ClusterIP or NodePort if needed