apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 5m # Reconcile every 5 minutes
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 45.6.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    prometheus:
      service:
        type: ClusterIP
    alertmanager:
      enabled: true