apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sample-app
  namespace: flux-system
spec:
  interval: 5m
  path: ./apps/sample
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
