apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- apps-kustomization.yaml
- ../../../apps/monitoring/prometheus-helmrelease.yaml
- ../../../apps/monitoring/grafana-helmrelease.yaml
- ../../minikube/flux-system/prometheus-helmrepository.yaml
- ../../minikube/flux-system/grafana-helmrepository.yaml