apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- apps-kustomization.yaml
- ../../monitoring/prometheus-helmrelease.yaml
- ../../monitoring/grafana-helmrelease.yaml
- ../../clusters/minikube/prometheus-helmrepository.yaml
- ../../clusters/minikube/grafana-helmrepository.yaml