apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- apps-kustomization.yaml

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  path: ./apps/monitoring  # Ensure this matches the repo path
  prune: true
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-apps