name: Deploy to Staging

on:
  push:
    branches:
      - main

jobs:
  call-reusable-deploy:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: staging
      image-tag: latest
    secrets:
      kubeconfig: ${{ secrets.KUBECONFIG_STAGING }}