name: Reusable Deployment Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      image-tag:
        required: true
        type: string
    secrets:
      kubeconfig:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Kubernetes
        run: |
          echo "Deploying to ${{ inputs.environment }} with image tag ${{ inputs.image-tag }}"
          echo "${{ secrets.kubeconfig }}" > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml
          kubectl get pods -n ${{ inputs.environment }}